trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Juckes
      name: Juckes/common-pipelines-templates

variables:
  - group: template-packer

jobs:
  - job: Build
    displayName: Init and Build and Save Azure Scale Set Image
    steps:
      # Step 1: Authenticate Azure Subscription
      - template: steps/azure_auth.yml@templates
        parameters:
          subscriptionId: $(SANDPIT_SUBSCRIPTION)

      # # Step 2: Load Environment Variables (Run tools.sh first)
      # - script: |
      #     sudo bash $(Build.Repository.LocalPath)/packer-work/images/tools.sh
      #   displayName: 'Load environment variables'

      # Step 3: Initialize Packer (After the environment is set up)
      - script: packer init .
        displayName: Packer init
        workingDirectory: $(Build.Repository.LocalPath)/packer-work/images

      # Step 4: Run Packer Build (Make sure TERRAFORM_VERSION is passed correctly)
      - script: |
          echo "TERRAFORM_VERSION: $(TERRAFORM_VERSION)"
          packer build -var "terraform_version=$(TERRAFORM_VERSION)" .
        displayName: Packer Build
        env:
          PKR_VAR_client_id: $(AZURE_SERVICE_PRINCIPAL_ID)
          PKR_VAR_client_secret: $(AZURE_SERVICE_PRINCIPAL_SECRET)
          PKR_VAR_subscription_id: $(SANDPIT_SUBSCRIPTION)
          PKR_VAR_tenant_id: $(AZURE_TENANT_ID)
          PKR_VAR_template_resource_group_name: $(templateResourceGroupName)
        workingDirectory: $(Build.Repository.LocalPath)/packer-work/images

    variables:
      templateResourceGroupName: packer

    workspace:
      clean: all
